### ISSUE TITLE
[REFACTOR] TEAM, PRESENTATION, PROGRAM 도메인의 null 처리 작업을 수행합니다.

### ISSUE THREAD

**Issue by rlajm1203** [JNU-econovation/EEOS-BE#159]
## 어떤 기능인가요?
> EEOS 3.0에서 새로 추가된 기능은 기존에 운영용에 존재하던 데이터로는 사용할 수 없습니다.
테이블에 새로운 컬럼이 하나 추가되면, 기존에 있는 데이터들은 NULL 값으로 채워지니 운영용 페이지에서는 오류가 발생합니다.

## 작업 상세 내용
- [ ] null이면 기본값으로 채운 후 저장
- [ ] 서버 시작 시, 데이터베이스 컬럼 초기화

**Comment by kssumin** [comment]
혹시 어떤 식으로 구현하실 건가요?

**Comment by rlajm1203** [comment]
> 혹시 어떤 식으로 구현하실 건가요?

ApplicationRunner 인터페이스를 구현하여, 애플리케이션이 모두 실행된 후

데이터베이스에 저장된 기존 데이터들의 새로운 필드에 값을 추가해주는 로직으로 구현하였습니다.
