### ISSUE TITLE
[FEAT] 사용자 로그를 기록합니다.

### ISSUE THREAD

**Issue by rlajm1203** [JNU-econovation/EEOS-BE#33]
## 어떤 기능인가요?
> 사용자 요청에 관한 로그를 기록합니다.

## 작업 상세 내용
- [ ] 텍스트 파일로 사용자 로그를 기록하여 저장합니다.

**Comment by kssumin** [comment]
1. 혹시 모든 사용자에 대해 정상/비성장 구분 없이 모든 로그를 기록하는 것인가요?
1-1. 또한 지금은 에러에 대해 로그를 적용하고 있는데요! 지금 설정되어 있는 로그와 다른 점이 궁금합니다.
2. 혹시 "정상/비정상 구분없이 모두 기록"이라면 왜 해당 기능이 필요한지도 궁긍합니다!

**Comment by rlajm1203** [comment]
@kssumin 
정상,비정상을 명시하지 않고 애매하게 작성했네요.

제가 생각했던 방식은 비정상인 경우는 기록하지 않고, 정상적인 로그만 기록으로 남겨서 나중에 어떤 사용자가 어떤 요청을 보냈는지 분석하면 좋을 것 같아서 추가했습니다!

모든 요청에 대해 기록할지, 일부 요청에만 기록할지 그건 논의가 필요해 보이네요~

그런데 그 전에 EEOS에서 현재 로그를 기록하는 게 과연 필요한 일인지 의문이 듭니다 만두님은 어떻게 생각하시나요? (물론 저는 있으면 좋고 없으면 그만이라는 생각입니다.)

**Comment by kssumin** [comment]
지금처럼 예상치 못 한 에러가 발생했을 시에 대한 로그는 반드시 있어야 한다고 봅니다.
(저희가 원인을 파악하기 위함)

하지만 사용자 로그를 기록한다면 추후 서비스의 확장성과 관련해서 
사용자가 이러한 요청을 자주하는 게 같은데 우리가 이런 요청을 앞단에 빼볼까?
든지 사용자의 로그를 기반으로 추후 기능을 생각해볼 수 있는 지표가 될 수 있을 것이라는 생각이 들어요!
[사용자 로그에 대한 문서 첨부](https://medium.com/@connect2yh/%EC%82%AC%EC%9A%A9%EC%9E%90-%ED%96%89%EB%8F%99-%EB%A1%9C%EA%B7%B8-%ED%8C%8C%EC%A2%85%EB%B6%80%ED%84%B0-%EC%88%98%ED%99%95%EA%B9%8C%EC%A7%80-%EC%9E%98-%EC%8C%93%EA%B8%B0-1%ED%8E%B8-9733422dd00d)

그래서 만약 사용자 로그를 기록한다고 한다면
우리가 어떤 식으로 사용자 로그를 설계해야하며
어떤 데이터를 수집할 지에 대한 범위가 정해진다면

그때는 eeos에서도 로그를 기록하는 것도 의미가 있을 거라는 생각이 듭니다!

**Comment by rlajm1203** [comment]
> ### 에러에 대한 로그
> 지금처럼 예상치 못 한 에러가 발생했을 시에 대한 로그는 반드시 있어야 한다고 봅니다. (에러 발생 시 에러 로그로 원인을 파악하기 위함)
> 
> ### 사용자 로그를 남겼을 때의 장점
> 하지만 사용자 로그를 기록한다면 추후 서비스의 기능과 관련해서 사용자가 실제로 이런 기능을 잘 호출하지 않은 것 같은데 이 기능을 빼볼까? 든지 사용자의 로그를 기반으로 추후 기능을 생각해볼 수 있는 지표가 될 수 있을 것이라는 생각이 들어요! [사용자 로그에 대한 문서 첨부](https://medium.com/@connect2yh/%EC%82%AC%EC%9A%A9%EC%9E%90-%ED%96%89%EB%8F%99-%EB%A1%9C%EA%B7%B8-%ED%8C%8C%EC%A2%85%EB%B6%80%ED%84%B0-%EC%88%98%ED%99%95%EA%B9%8C%EC%A7%80-%EC%9E%98-%EC%8C%93%EA%B8%B0-1%ED%8E%B8-9733422dd00d) [로그 데이터에 대한 문서 첨부](https://techblog.woowahan.com/2536/)
> 
> ### 우리 서비스에서는 사용자 로그가 필요할까?
> 다만 저희는 동아리 내부 서비스이기 때문에 사용자의 피드백을 다른 외부 서비스보다는 많이 받고 있는 환경이라고 생각해요! 실제로 사용자분들이 피드백을 직접 많이 해주시구요! 그래서 우선순위는 낮게 가져가도 될 것 같다는 생각입니다! 그렇지만 이 로그 관리를 이번에 고민해보고 싶으시면 적용하는 것도 적극 환영이에요! 👍
> 
> `혹시 @rlajm1203 님께서는 현재 저희 서비스에서 로그의 필요성을 얼마나 느끼고 계신지도 궁금합니다!`
> 
> ### 이 기능을 구현하기 전에 아래와 같은 사항이 우선시되어야 한다고 생각합니다!
> 다만 이 사용자 로그에 대한 기능이 의미가 있어지려면
> 
> 1. `어떤 목적`으로 이러한 기능을 만드는 것이며(즉 로그 데이터를 어디에 사용할지)
> 2. 이러한 목적을 이루기 위해서 로그를 어떤 범위까지 수집할 것이며
> 3. 로그 데이터를 잘 분석하기 위해서는 로그 데이터 설계를 어떻게 할 것인지가 명확해야 한다고 생각합니다!

@kssumin 
음, Mando님께서 남겨주신 코멘트를 읽고 생각해봤는데 EEOS 서비스는 출석 체크 용도로 많이 사용하고 있고,
사용자가 언제 사용하는지 거의 정확하게 예측이 가능합니다. (주로 주간발표 출석체크)
이러한 점으로 미뤄 보았을 때, 사용자 로그를 수집하는 기능은 당장 필요하지 않다는 생각이 드네요~
